# port
server:
  port: 8282

# database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shiro_boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: qwe123

#mybatis
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: top.itdn.server.entity

