server:
  port: 8081
spring:
  application:
    name: admin-server
  datasource:
    url: jdbc:mysql://localhost:3306/shiro_boot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
mybatis:
  mapperLocations: classpath:/mapper/*.xml
#  redis:
#    host: 127.0.0.1
#    port: 6379


