server:
  port: 8081
spring:
  application:
    name: admin-server
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/jwt_shiro?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#    username: root
#    password: 123qwe
#  mybatis:
#    mapper-locations: classpath:mapper/*.xml
#    type-aliases-package: com.itdn.serverend.dao
#  redis:
#    host: 127.0.0.1
#    port: 6379


